### ISSUE TITLE
Convert DB to MySql

### ISSUE THREAD

**Issue by TheCois** [TheCois/KingRoofingApp#4]
This is pending approval of Bill / Len

**Comment by TheCois** [comment]
The database as it is currently is a SQL Server instance.
Using it it brings two issues:
-  licensing costs
- limited deployment scenarios [security options favor Windows machines only]
- ease of configuration

I suggest using MySql as there are free options, deployment is universal, and more easily automate-able.

**Comment by TheCois** [comment]
this is done

**Comment by maxalmonte14** [comment]
You should close this issue, otherwise it will continue appearing in Github searches 👍
